/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adderMul_27 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg z,
    output reg v,
    output reg n,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] temp;
  
  wire [16-1:0] M_multi_mul;
  reg [16-1:0] M_multi_a;
  reg [16-1:0] M_multi_b;
  multiply_31 multi (
    .a(M_multi_a),
    .b(M_multi_b),
    .mul(M_multi_mul)
  );
  
  always @* begin
    M_multi_a = a[0+15-:16];
    M_multi_b = b[0+15-:16];
    
    case (alufn[0+1-:2])
      2'h0: begin
        temp = a + b;
        v = (a[15+0-:1] & b[15+0-:1] & (~temp[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & temp[15+0-:1]);
      end
      2'h1: begin
        temp = a - b;
        v = (a[15+0-:1] & (~b[15+0-:1]) & (~temp[15+0-:1])) | ((~a[15+0-:1]) & (b[15+0-:1]) & temp[15+0-:1]);
      end
      2'h2: begin
        temp = M_multi_mul;
        v = (a[15+0-:1] & b[15+0-:1] & (~temp[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & temp[15+0-:1]);
      end
      2'h3: begin
        temp = a - (a / b * b);
        v = (a[15+0-:1] & b[15+0-:1] & (~temp[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & temp[15+0-:1]);
      end
      default: begin
        temp = a + b;
        v = (a[15+0-:1] & b[15+0-:1] & (~temp[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & temp[15+0-:1]);
      end
    endcase
    z = (~|temp);
    n = temp[15+0-:1];
    out = temp;
  end
endmodule
