/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module btnDebouncer_7 (
    input clk,
    input btn_in,
    output reg btn_out
  );
  
  
  
  localparam OFF_bd = 1'd0;
  localparam ON_bd = 1'd1;
  
  reg M_bd_d, M_bd_q = OFF_bd;
  
  always @* begin
    M_bd_d = M_bd_q;
    
    M_bd_d = M_bd_q;
    btn_out = 1'h0;
    
    case (M_bd_q)
      ON_bd: begin
        if (btn_in == 1'h1) begin
          btn_out = 1'h1;
          M_bd_d = OFF_bd;
        end
      end
      OFF_bd: begin
        if (btn_in == 1'h1) begin
          
        end
        M_bd_d = ON_bd;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_bd_q <= M_bd_d;
  end
  
endmodule
