/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sevenSeg_25 (
    input [6:0] char,
    output reg [6:0] seg
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        seg = 7'h3f;
      end
      1'h1: begin
        seg = 7'h06;
      end
      2'h2: begin
        seg = 7'h5b;
      end
      2'h3: begin
        seg = 7'h4f;
      end
      3'h4: begin
        seg = 7'h66;
      end
      3'h5: begin
        seg = 7'h6d;
      end
      3'h6: begin
        seg = 7'h7d;
      end
      3'h7: begin
        seg = 7'h07;
      end
      4'h8: begin
        seg = 7'h7f;
      end
      4'h9: begin
        seg = 7'h6f;
      end
      7'h61: begin
        seg = 7'h77;
      end
      7'h62: begin
        seg = 7'h7c;
      end
      7'h63: begin
        seg = 7'h39;
      end
      7'h64: begin
        seg = 7'h5e;
      end
      7'h65: begin
        seg = 7'h79;
      end
      7'h68: begin
        seg = 7'h74;
      end
      7'h6c: begin
        seg = 7'h38;
      end
      7'h6d: begin
        seg = 7'h15;
      end
      7'h6e: begin
        seg = 7'h37;
      end
      7'h6f: begin
        seg = 7'h5c;
      end
      7'h70: begin
        seg = 7'h73;
      end
      7'h71: begin
        seg = 7'h67;
      end
      7'h72: begin
        seg = 7'h50;
      end
      7'h73: begin
        seg = 7'h6d;
      end
      7'h74: begin
        seg = 7'h78;
      end
      7'h75: begin
        seg = 7'h3e;
      end
      7'h78: begin
        seg = 7'h76;
      end
      default: begin
        seg = 7'h00;
      end
    endcase
  end
endmodule
